# Generated by Django 3.0 on 2020-01-08 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sign',
            name='password',
            field=models.CharField(default='NULL', max_length=10),
        ),
    ]
